@startuml
actor User

participant ":LongAh"
participant ":Group"
participant ":Command"
participant ":MemberList"
participant ":TransactionList"
participant ":Transaction"
participant ":UI"


ref over "User" , ":Command"
Command Execution Sequence
(addTransaction)
end ref
":Group" -> ":MemberList" : Get members
":MemberList" --> ":Group" : members
":Group" -> ":TransactionList" : Get transactions
":TransactionList" --> ":Group" : transactions
alt Valid transaction format
    ":Group" -> ":TransactionList": Add transaction
    ":TransactionList" -> ":Transaction": Add transaction
    ":Transaction" -> ":UI": "Transaction added successfully"
    ":Transaction" -> ":UI": Transaction details
    ":Group" -> ":Group": Update members balance
    ":Group" -> ":Group": Update transaction solution
    ":Logger" -> ":Logger": log(Level.INFO, "Transaction solution updated")
else Invalid transaction format
    ":Transaction" -> ":UI": "Invalid transaction format"
end

@enduml