@startuml
actor User

participant ":LongAh"
participant ":Group"
participant ":Command"
participant ":MemberList"
participant ":TransactionList"
participant ":Transaction"


ref over "User" , ":Command"
Command Execution Sequence
(addTransaction)
end ref
":Group" -> ":MemberList" : Get members
":MemberList" --> ":Group" : members
":Group" -> ":TransactionList" : Get transactions
":TransactionList" --> ":Group" : transactions
":Group" -> ":TransactionList": Add transaction
alt Valid transaction format
    ":TransactionList" -> ":Transaction": Add transaction
    ":Transaction" --> ":TransactionList": Transaction added
    ":TransactionList" --> ":Group": Update transaction list
    ":Group" --> "User": Transaction details
    ":Group" -> ":Group": Update members balance
    ":Group" -> ":Group": Update transaction solution
else Invalid transaction format
    ":TransactionList" -> ":Group": Invalid transaction format
    ":Group" --> "User" : "Invalid transaction format"
end

@enduml