@startuml
participant ":TransactionList" as Foo
participant ":Transaction" as Foo1
participant ":DateTime" as Foo2
[->      Foo:""filterTransactionsEqualToDateTime(dateTimeExpression)""
Foo -> Foo2:new DateTime(dateTimeExpression)
Foo2 --> Foo: DateTime object of user input created
loop for transaction in transactions
    Foo -> Foo1: transaction.getTransactionTime()
    Foo1 --> Foo: DateTime object of transaction
    Foo -> Foo2: transactionDateTime.isEqual(userDateTime)
    Foo2 --> Foo: Boolean determining whether the two dateTimes are equal
end
@enduml