@startuml
participant ":Transaction" as Foo
participant ":DateTime" as Foo1
[->      Foo:""toString()""
alt transaction has dateTime
    Foo -> Foo1:toString()
    Foo1 --> Foo: String representing dateTime
    Foo -> Foo: added String dateTime to printout
end
@enduml